### ISSUE TITLE
How to create an API

### ISSUE THREAD

**Issue by spil-peter-lorent** [gigafied/minion#7]
From the HTML wrapper, I need access to some methods in some of my own classes (instances in an already bootstrapped application) that extend minion.class or minion.singleton. What is the best way to accomplish this?

I was thinking I should use minion.get but all I'm getting is:

Uncaught TypeError: Object function ()
{
    if (arguments[0] !== "**no_init**")
    {
        /*
            Handy for referencing dependencies. If a Class requires example.Test, then you can reference said class
            in any method by this.__imports.Test;

```
    */
    if (!_class.prototype.hasOwnProperty("__imports"))
    {
        _class.prototype.__imports = minion.use(this.__dependencies, {});
    }

    if (!this.__preInit)
    {
        for (var attr in _perInstanceProps)
        {
            if (_perInstanceProps.hasOwnProperty(attr))
            {
                this[attr] = _copyTo({}, _perInstanceProps[attr]);
            }
        }

        // All real construction is actually done in the init method
        return this.init.apply(this, arguments);
    }
    else
    {
        return this.__preInit.apply(this, arguments);
    }

}
```

} has no method 'getProxyName'

**Comment by gigafied** [comment]
Can you please share some of your code? Hard to figure out without some proper context.

**Comment by plorent** [comment]
Sure. First of all, I'm using minion together with a javascript port of PureMVC (puremvc.org). I think you will be familiar with PureMVC but if not... it uses Facade, Command, Proxy and Mediator patterns on top of a MVC triangle. I'm prototyping a single page application, obviously.

Bootstrapping from the html wrapper looks something like this:

<pre lang="javascript"><code>
<script type="text/javascript">
        function initApp() {
            minion.configure({
                classPath : "src"
            });
            minion.require(["application.Application"], function(Application)
            {
                var app = new Application();
                app.startup();
            })
        };
 </script>
</code></pre>

The Application class:

<pre lang="javascript"><code>
minion.define("application", {
    require : [
        "core.facade.Facade",
        "application.control.PrepareModelCommand",
        "application.control.TestCommand",
        "application.model.TestProxy"
    ],
    Application : minion.extend("minion.Class", {
        startup : function ()
        {
            var facade = this.__imports.Facade.getInstance();
            facade.initializeFacade();
            facade.registerCommand("TestCommand", this.__imports.TestCommand);
            facade.registerCommand("PrepareModelCommand", this.__imports.PrepareModelCommand);
            facade.registerProxy(new this.__imports.TestProxy("TestProxy"));
            facade.sendEvent("PrepareModelCommand");
        }
    })
});
</code></pre>

By triggering the PrepareModelCommand, some data gets loaded, PrepareModelCommand will fire another event that builds a UI, etc, etc... you get the point.

Now, the requirements of the application demand that I can call public methods from scripts in the html wrapper. What it boils down to is that the application can prefetch content and once the targeted DOM element is there, it shows the content. Something like: 

<pre lang="javascript"><code>
<script>Front.push('id of the div here');</script>
</code></pre>

Of course the Facade in my application simplifies the API behind it and a simple solution to my problem is to make the facade a global in the startup function shown above. In the html wrapper, this would then allow me to do something like:

<pre lang="javascript"><code>
<script>
facade.sendEvent("PrepareViewCommand", "id of the div here");
</script>
</code></pre>

Which is a nice solution, in the spirit of the PureMVC framework.

But, working with Minion, and with future requirements of other applications in my mind, I would still like to know if there is a way I can make some methods in my classes public. Something in the spirit of a revealing module pattern maybe?

**Comment by gigafied** [comment]
In JavaScript, everything is 'public' so to speak, so as long as you expose an instance, method or Class globally, you should be able to do this.

`minion.get()` will only work if you have already loaded the Class you are trying to get with a previous call to `minion.require()`.

Think of it as an alternative to `this.__imports`, it can work in other places too, but generally should be avoided as you always are assuming 'I have already loaded X Class', but by using `minion.get()` you are essentially tightly coupling code in places that you may not realize you are doing it.

So, if the only place you are loading `ClassZ` is from `ClassA` and you are calling `minion.get("example.ClassZ")` somewhere, if you refactor and find that you no longer need `ClassA` things will break and you'll have no easy way to determine why.

This is why I didn't really document `minion.get()` anywhere. You should be able to find an alternative solution.

If you want one place where you can expose global API's I'd recommend a separate, detached call to `minion.require` which would look something like the below:

```
minion.require(["core.facade.Facade", "application.some.Thing"], function(Facade, Thing) {
    window.facade = Facade.getInstance();
    window.thing = new Thing();
});
```

Hope this helps.

**Comment by plorent** [comment]
The detached call to minion.require does the trick just fine. I like it, thanks!

**Comment by gigafied** [comment]
Great, glad I could help!
